### PR TITLE
Draggable pill update

### PR DESCRIPTION
**Pull request by smilerz**
provide visual cue that pills are draggable

### CODE REVIEW

**Comment by vabene1111** [comment]
can you rebase this on the latest develop so i dont have to merge all the generated javascript files? really need to get around to removing them from the repo

**Comment by smilerz** [comment]
can you tag this as hacktober?

**Comment by vabene1111** [comment]
can you test if this is required ? because the repo has hacktoberfest as a topic and the PR got merged, this should already count (just want to know if it works for my PRs as well 😂 )

**Comment by vabene1111** [comment]
You can see that on your profile page https://hacktoberfest.digitalocean.com/profile

**Comment by smilerz** [comment]
Looks like its a bad test - the PRs were created before Oct 1.

> Pull requests created before Oct 1 but merged or marked as ready for review after do not count.

**Comment by vabene1111** [comment]
haha that bad, but i am sure there are plenty small things that you can PR to get your 4 PR's

**Pull request merged**
