### PR TITLE
Update docker-publish-dev.yml

### PR DESCRIPTION
**Pull request by cesarblancg**
Added more target platforms to develop tags on docker hub.

#358

### CODE REVIEW

**Comment by vabene1111** [comment]
This is a nice idea but to be honest i often push breaking changes to develop so its not really recommended to use that branch. 

Apart from that i also use develop to deploy to my server for testing and buildx for all plattforms takes something like an hour or so to build so it would make testing even harder for me than it already is.

What do you think of a beta branch ? basically develop but i only merge it when its not completely broken 😂

**Comment by cesarblancg** [comment]
I like the idea of a beta branch.

**Comment by vabene1111** [comment]
ok then i will implement that 👍

**Comment by vabene1111** [comment]
ok so i added a beta branch and used the code you provided in this PR, in about an hour the release should be out. I would really love some feedback so feel free to post ideas, wishes, feedback, etc. from what you see on the beta branch so i can improve on it. 

I currently dont have a good way of making beta changelogs as i dont really feel like always making  a new release but most things should be obvious. 

Also: Even tough it is a "offical" beta release i cannot guarantee that things will be working all the time. There might be broken versions and backpatching is currently NOT supported or at least at your own hand.

**Comment by vabene1111** [comment]
Ok something is broken in the buildx action, either its something i broke with the dockerfile or the action is broken 

https://github.com/vabene1111/recipes/runs/1783285924

need to figure this out first

**Comment by vabene1111** [comment]
ok so for whatever reason the  first run failed but the second one worked. Beta image is now released on docker hub.

https://hub.docker.com/layers/vabene1111/recipes/beta/images/sha256-99566832ed0fa5e212d56609183a8627e747bddc79abd0c0f622df1d75aad78f?context=explore

if i start forgetting about it feel free to let me know :)

**Pull request closed without merging**
