### PR TITLE
added 'webdav_root' option

### PR DESCRIPTION
**Pull request by pataya23**
otherwise I get an error (webdav3.exceptions.RemoteResourceNotFound: Remote resource: </path> not found)

### CODE REVIEW

**Comment by vabene1111** [comment]
what is the nextcloud/owncloud/webdav server (and version) you are using ? because it works for me with my nextcloud 18.02

But i will test it and if it works for my version as well i see no reason to change it

**Comment by pataya23** [comment]
same here, nextcloud with 18.0.2. interesting...

**Comment by vabene1111** [comment]
ok, i will quickly test it and if it works i see no reason to keep the old Version as the `webdav_root` option seems to be exactly for this.

**Comment by vabene1111** [comment]
ok i have tested it with my nextcloud and it seems to work as expected, thanks for the PR!

**Pull request merged**
