### PR TITLE
Create image_processing.py

### PR DESCRIPTION
**Pull request by MaxJa4**
Added central function to rescale and compress images for recipes (or in general).
Switched from previously used PNG format to 75% JPEG format for a 5-10x file size reduction with hardly any quality loss.

### CODE REVIEW

**Comment by MaxJa4** [comment]
Feel free to move this file to a more suitable location as you see fit.

**Comment by vabene1111** [comment]
thanks very much, i will take a look at implementing this accross the application

**Comment by MaxJa4** [comment]
Maybe a one time execution after the next update containing this feature would be a good idea to compress all already existing pictures.

I'm gonna make a little test and do that with my instance manually to see how much smaller the overview page gets and how faster it loads (the first time, since caching is active on my page).

**Comment by vabene1111** [comment]
i am always worried with file migrations but you are generally right .. we will see what can be done after installing

**Comment by MaxJa4** [comment]
That's true... maybe implementing it in one version and migrating the existing files (just PNGs) in the follow version reduces that migration risk a little since the new compression has been tested live already (which should be fine but you never know).

**Comment by MaxJa4** [comment]
Previous format (like there were rescaled before; 70% PNG; reload without caching):
image

New format (75% JPEG optimized; reload without caching):
image

This was on the /search/ site (my default site). I'd call it a success :)

**Comment by vabene1111** [comment]
i think that sounds very good 👍

**Pull request merged**
