### PR TITLE
Manually Import Recipe

### PR DESCRIPTION
**Pull request by smilerz**
This is a major rework of the url_import form.  Some of it might (probably is) a bit cludgy, I'm happy to take feedback on any areas that need reworked.

- Automatically importing from url works the same as prior version.
- Importing from external app also works the same - but has been moved to the same form.
- Added several additional methods to import:
1. retrieve from url - manual import
2. paste json or html text - automatic import
3. paste json or html text - manual import

some of the manual import might still be buggy - but the existing automated imports should continue to work as before.

here are a couple of screenshots of the updated form:
image
image
image

### CODE REVIEW

**Comment by vabene1111** [comment]
This looks increadible 👍 thank you so much for putting all that work into it.

I will review it in the following days and give you feedback where necessary.

**Comment by vabene1111** [comment]
hey @smilerz thanks for all your recent contributions. Do you think we could have a quick chat anytime the next few days ? 

here is my discord handle `vabene1111#5492` but if you prefer any other means of communication feel free to tell me what you like.

**Comment by smilerz** [comment]
I'm done messing with this PR for now.  it now includes tests (all of which now pass!)  Sorry for the constant updates on this one - I should have waited to submit the PR until it was actually done.

**Comment by smilerz** [comment]
@vabene1111 the CodeQL is failing on files added for automated tests - is there a way to exclude those types of docs from the CodEQL tests?

**Comment by vabene1111** [comment]
good question 🤔 i basically did the super easy github example code QL scanning thing. 

I think the easiest solution is for me to just dismiss the security warning after i merged it since its not relevant.

**Comment by smilerz** [comment]
> good question 🤔 i basically did the super easy github example code QL scanning thing.
> 
> I think the easiest solution is for me to just dismiss the security warning after i merged it since its not relevant.

OK - if you need me to change something just let me know.

**Comment by vabene1111** [comment]
awesome! I was playing around with openapi-generator yesterday, i hope to get that stuff out of the way in the next few days/weeks and get to this PR after that.

**Pull request merged**
